Repository QRaimbault/SI_ESPACE, pull requests merged in 2018-06, with the labels that each got.

#2 🙈 Update gitignore
  symfony/.gitignore
Labels: enhancement

#4 Front demo
  frontend-code/.eslintrc.js
  frontend-code/package.json
  frontend-code/public/index.html
  frontend-code/src/js/Classes/User.js
  frontend-code/src/js/app.js
  frontend-code/yarn.lock
  symfony/src/Entity/Parking.php
  symfony/src/Migrations/Version20180621094715.php
  symfony/src/Repository/ParkingRepository.php
Labels: enhancement

#10 Multiple Doctrine Entities implementation
  symfony/.gitignore
  symfony/.php_cs.dist
  symfony/composer.json
  symfony/composer.lock
  symfony/src/Controller/API/DummyController.php
  symfony/src/Entity/AdditionalService.php
  symfony/src/Entity/Order.php
  symfony/src/Entity/Parking.php
  symfony/src/Entity/SpaceShip.php
  symfony/src/Entity/User.php
  symfony/src/Migrations/Version20180621094715.php
  symfony/src/Migrations/Version20180621103802.php
  symfony/src/Repository/AdditionalServiceRepository.php
  symfony/src/Repository/OrderRepository.php
  symfony/src/Repository/SpaceShipRepository.php
  symfony/src/Repository/UserRepository.php
  symfony/symfony.lock
Labels: feature

#14 Security system
  .gitignore
  symfony/composer.json
  symfony/composer.lock
  symfony/config/packages/security.yaml
  symfony/config/routes.yaml
  symfony/src/Controller/API/SpaceShipController.php
  symfony/src/Controller/API/UserController.php
  symfony/src/Controller/ParkingController.php
  symfony/src/Controller/SpaceShipController.php
  symfony/src/DataFixtures/UserFixtures.php
  symfony/src/Entity/AdditionalService.php
  symfony/src/Entity/Order.php
  symfony/src/Entity/Parking.php
  symfony/src/Entity/SpaceShip.php
  symfony/src/Entity/User.php
  symfony/src/Form/ParkingType.php
  symfony/src/Form/SpaceShipType.php
  symfony/src/Migrations/Version20180621103802.php
  symfony/src/Migrations/Version20180623104136.php
  symfony/src/Repository/AdditionalServiceRepository.php
  symfony/symfony.lock
  symfony/templates/parking/_delete_form.html.twig
  symfony/templates/parking/_form.html.twig
  symfony/templates/parking/edit.html.twig
  symfony/templates/parking/index.html.twig
  symfony/templates/parking/new.html.twig
  symfony/templates/parking/show.html.twig
  symfony/templates/space_ship/_delete_form.html.twig
  symfony/templates/space_ship/_form.html.twig
  symfony/templates/space_ship/edit.html.twig
  symfony/templates/space_ship/index.html.twig
  symfony/templates/space_ship/new.html.twig
  symfony/templates/space_ship/show.html.twig
Labels: feature, need review

#17 Front login page
  frontend-code/.babelrc
  frontend-code/.eslintignore
  frontend-code/.eslintrc.js
  frontend-code/.gitignore
  frontend-code/.sass-lint.yml
  frontend-code/README.md
  frontend-code/bin/dev-server.js
  frontend-code/bin/lib/open-browser.js
  frontend-code/bin/spa-server.js
  frontend-code/gulpfile.js
  frontend-code/jsconfig.json
  frontend-code/package.json
  frontend-code/public/index.html
  frontend-code/src/components/App/App.vue
  frontend-code/src/components/Register/Form.vue
  frontend-code/src/components/Register/Steps.vue
  frontend-code/src/js/Classes/User.js
  frontend-code/src/js/app.js
  frontend-code/src/main.js
  frontend-code/src/router/index.js
  frontend-code/src/scss/components/RegisterForm.scss
  frontend-code/src/scss/components/RegisterSteps.scss
  frontend-code/src/scss/global/master.scss
  frontend-code/src/scss/global/partials/_functions.scss
  frontend-code/src/scss/global/partials/_mixins.scss
  frontend-code/src/scss/global/partials/_reset.scss
  frontend-code/src/scss/global/partials/_variables.scss
  frontend-code/src/scss/views/Index.scss
  frontend-code/src/scss/views/Login.scss
  frontend-code/src/scss/views/Register.scss
  frontend-code/src/views/Index.vue
  frontend-code/src/views/Login.vue
  frontend-code/src/views/Register.vue
  frontend-code/static/index.html
  frontend-code/webpack.config.js
  frontend-code/yarn.lock
  symfony/src/Controller/API/UserController.php
  symfony/src/DataFixtures/UserFixtures.php
  symfony/src/Entity/User.php
  symfony/src/Migrations/Version20180621094715.php
  symfony/src/Migrations/Version20180621103802.php
  symfony/src/Migrations/Version20180623104136.php
  symfony/src/Migrations/Version20180624104654.php
  symfony/src/Service/UserService.php
Labels: feature

#23 ✨ Introducing DataStore
  frontend-code/jsconfig.json
  frontend-code/src/datastore/index.js
  frontend-code/src/views/Login.vue
  frontend-code/src/views/Register.vue
  frontend-code/webpack.config.js
Labels: feature

#24 🐛 Fix dat bitch form on register
  frontend-code/src/components/App/App.vue
  frontend-code/src/components/Register/Form.vue
  frontend-code/src/router/index.js
  frontend-code/src/views/Register.vue
Labels: bug

#27 Login system
  composer.json
  frontend-code/src/APIHelper.js
  frontend-code/src/components/Register/Form.vue
  frontend-code/src/datastore/index.js
  frontend-code/src/main.js
  frontend-code/src/router/index.js
  frontend-code/src/scss/views/Login.scss
  frontend-code/src/views/Login.vue
  frontend-code/src/views/Register.vue
  nginx/symfony.conf
  symfony/.env.dist
  symfony/composer.json
  symfony/composer.lock
  symfony/config/bundles.php
  symfony/config/packages/nelmio_cors.yaml
  symfony/src/Controller/API/UserController.php
  symfony/symfony.lock
Labels: feature

#30 Handle account registration API
  frontend-code/src/components/Register/Form.vue
  frontend-code/src/datastore/index.js
  frontend-code/src/views/Register.vue
  symfony/src/Entity/User.php
Labels: feature

#39 🏗 36
  frontend-code/src/components/Helper/Background.vue
  frontend-code/src/scss/components/HelperBackground.scss
  frontend-code/src/scss/views/Register.scss
  frontend-code/src/views/Register.vue
Labels: UI, feature, need review

#40 Front landing page
  frontend-code/src/scss/components/HelperBackground.scss
  frontend-code/src/scss/components/RegisterForm.scss
  frontend-code/src/scss/views/Index.scss
  frontend-code/src/views/Index.vue
  frontend-code/src/views/Login.vue
Labels: UI, feature, need review

#46 Login UI (mobile) #35
  frontend-code/src/scss/components/HelperBackground.scss
  frontend-code/src/scss/views/Index.scss
  frontend-code/src/scss/views/Login.scss
  frontend-code/src/views/Login.vue
Labels: UI, feature, need review

#47 SpaceShip & User controller
  symfony/src/Controller/API/DummyController.php
  symfony/src/Controller/API/SpaceShipController.php
  symfony/src/Controller/API/UserController.php
  symfony/src/Controller/ParkingController.php
  symfony/src/Controller/SpaceShipController.php
  symfony/src/Service/SpaceShipService.php
Labels: API, feature

#48 User dashboard
  frontend-code/.sass-lint.yml
  frontend-code/src/datastore/index.js
  frontend-code/src/img/waves.png
  frontend-code/src/router/index.js
  frontend-code/src/scss/global/partials/_fonts.scss
  frontend-code/src/scss/views/Dashboard.scss
  frontend-code/src/views/Dashboard.vue
  frontend-code/src/views/Login.vue
  frontend-code/src/views/UserInfos.vue
Labels: UI, feature, need review

#49 Controllers
  frontend-code/src/components/App/App.vue
  frontend-code/src/components/Register/Form.vue
  frontend-code/src/datastore/index.js
  frontend-code/src/views/Login.vue
  frontend-code/src/views/Register.vue
  symfony/src/Controller/API/UserController.php
Labels: API, feature

#51 🏗 Use VueX as a state manager instead of datastore
  frontend-code/package.json
  frontend-code/src/components/App/App.vue
  frontend-code/src/datastore/index.js
  frontend-code/src/main.js
  frontend-code/src/store.js
  frontend-code/src/views/Confirmation.vue
  frontend-code/src/views/Dashboard.vue
  frontend-code/src/views/Login.vue
  frontend-code/src/views/Register.vue
  frontend-code/src/views/UserInfos.vue
  frontend-code/yarn.lock
Labels: API, feature

#52 💄 Completed footer component
  frontend-code/src/components/Helper/Footer.vue
  frontend-code/src/scss/components/Footer.scss
  frontend-code/src/views/UserInfos.vue
Labels: UI, feature, need review

#53 Some API documentation
  frontend-code/src/APIHelper.js
  frontend-code/src/components/App/App.vue
  frontend-code/src/views/Dashboard.vue
  frontend-code/static/index.html
  nginx/Dockerfile
  php-fpm/create-database.sh
  symfony/composer.json
  symfony/composer.lock
  symfony/config/bundles.php
  symfony/config/packages/nelmio_api_doc.yaml
  symfony/config/routes.yaml
  symfony/config/routes/nelmio_api_doc.yaml
  symfony/src/Controller/API/SpaceShipController.php
  symfony/src/Controller/API/UserController.php
  symfony/src/Entity/SpaceShip.php
  symfony/src/Entity/User.php
  symfony/symfony.lock
Labels: API, feature

#57 Front user infos
  frontend-code/src/components/Helper/Background.vue
  frontend-code/src/components/Helper/StaticBackground.vue
  frontend-code/src/scss/components/Footer.scss
  frontend-code/src/scss/components/HelperStaticBackground.scss
  frontend-code/src/scss/views/Dashboard.scss
  frontend-code/src/scss/views/UserInfos.scss
  frontend-code/src/views/Dashboard.vue
  frontend-code/src/views/Register.vue
  frontend-code/src/views/UserInfos.vue
Labels: UI, feature, need review

#61 💄 Completed register steps as component
  frontend-code/src/components/Helper/StaticBackground.vue
  frontend-code/src/components/Register/Steps.vue
  frontend-code/src/scss/components/RegisterSteps.scss
  frontend-code/src/scss/views/Login.scss
  frontend-code/src/views/Login.vue
  frontend-code/src/views/Register.vue
Labels: UI, feature, need review

#62 💄 Completed login loader style
  frontend-code/src/img/logo.png
  frontend-code/src/scss/views/Login.scss
  frontend-code/src/views/Login.vue
Labels: UI, feature, need review

#68 Added frontend booking page
  frontend-code/package-lock.json
  frontend-code/src/components/Booking/Form.vue
  frontend-code/src/components/Booking/Steps.vue
  frontend-code/src/img/alpha.png
  frontend-code/src/router/index.js
  frontend-code/src/scss/components/BookingForm.scss
  frontend-code/src/scss/global/partials/_variables.scss
  frontend-code/src/scss/views/Booking.scss
  frontend-code/src/views/Booking.vue
  frontend-code/src/views/Bookingadd.vue
  frontend-code/src/views/Bookingconfirmation.vue
  frontend-code/src/views/Login.vue
  frontend-code/src/views/Register.vue
Labels: UI, feature

#69 💄 Completed Activity Page
  frontend-code/package-lock.json
  frontend-code/src/components/Activity/Articles.vue
  frontend-code/src/img/Activite/Maxdefault.jpg
  frontend-code/src/img/Activite/Ski.jpg
  frontend-code/src/img/Activite/Surf.jpg
  frontend-code/src/img/Activite/nightclub.jpg
  frontend-code/src/router/index.js
  frontend-code/src/views/Activity.vue
Labels: UI, feature

#70 Restauration page
  frontend-code/src/components/Restoration/Articles.vue
  frontend-code/src/img/restauration/plat1.jpg
  frontend-code/src/img/restauration/plat2.jpg
  frontend-code/src/img/restauration/plat3.jpg
  frontend-code/src/img/restauration/plat4.jpg
  frontend-code/src/img/restauration/plat5.jpg
  frontend-code/src/router/index.js
  frontend-code/src/views/Restauration.vue
Labels: UI, feature, need review

#72 Home page
  frontend-code/.DS_Store
  frontend-code/package-lock.json
  frontend-code/src/components/Category/Category.vue
  frontend-code/src/components/Helper/Footer.vue
  frontend-code/src/components/Helper/Header.vue
  frontend-code/src/img/11b7f61a5e_57222_lilypad-callebaut-04-underwater-view.jpg
  frontend-code/src/img/Activities/Boitedenuit.jpg
  frontend-code/src/img/Activities/Ski-Dubai-2.jpg
  frontend-code/src/img/Activities/Surfimage.jpg
  frontend-code/src/img/Activities/maxresdefault.jpg
  frontend-code/src/img/Car/Roewe-Mobiliant-Concept-02-720x540.jpg
  frontend-code/src/img/Car/concept_2.jpg
  frontend-code/src/img/Car/giugiaro-gea-limousine-du-futur-800x.jpg
  frontend-code/src/img/Car/honda-3r-c-0_1440x655c.jpg
  frontend-code/src/img/Car/vehicule-2.jpg
  frontend-code/src/img/Car/vehicule.jpg
  frontend-code/src/img/Car/voitureespacefond.jpg
  frontend-code/src/img/Hotel/HomePicture.jpg
  frontend-code/src/img/Restoration/11f1d743-c71c-49ed-892c-654bb96b8077.jpg
  frontend-code/src/img/Restoration/97e83a9e-1db9-45a6-924c-4986341c97a0.jpg
  frontend-code/src/img/Restoration/aa13ce0e-9811-4a63-a5a2-091e3618798f.jpg
  frontend-code/src/img/Restoration/aca71aff-d17b-45ff-9ffd-ccc4d5c0149e.jpg
  frontend-code/src/img/Restoration/forumFull.jpg
  frontend-code/src/img/Yes.png
  frontend-code/src/img/logo.png
  frontend-code/src/img/waves.png
  frontend-code/src/main.js
  frontend-code/src/router/index.js
  frontend-code/src/scss/components/.gitignore
  frontend-code/src/scss/components/Category.scss
  frontend-code/src/scss/components/Footer.scss
  frontend-code/src/scss/components/Header.scss
  frontend-code/src/scss/components/HelperBackground.scss
  frontend-code/src/scss/global/partials/_variables.scss
  frontend-code/src/scss/views/Homepage.scss
  frontend-code/src/scss/views/UserInfos.scss
  frontend-code/src/views/Dashboard.vue
  frontend-code/src/views/Homepage.vue
  frontend-code/src/views/Index.vue
  frontend-code/src/views/Login.vue
  frontend-code/src/views/Register.vue
  frontend-code/src/views/UserInfos.vue
Labels: UI, feature, need review

#76 UI general review
  frontend-code/src/components/Helper/Background.vue
  frontend-code/src/components/Helper/Header.vue
  frontend-code/src/components/Helper/StaticBackground.vue
  frontend-code/src/scss/components/Category.scss
  frontend-code/src/scss/components/Header.scss
  frontend-code/src/scss/components/RegisterForm.scss
  frontend-code/src/scss/components/RegisterSteps.scss
  frontend-code/src/scss/global/partials/_variables.scss
  frontend-code/src/scss/views/Homepage.scss
  frontend-code/src/scss/views/Login.scss
  frontend-code/src/views/Homepage.vue
Labels: UI, feature, need review
